---
# tasks file for node_exporter_role

# Create Prometheus Group
- name: Create Prometheus Group
  group:
    name: prometheus
    state: present
  become: true

# Create Prometheus User
- name: Create Prometheus users
  user:
    name: prometheus
    comment: Prometheus User
    create_home: no
    group: prometheus
    shell: /sbin/nologin
    state: present
  become: true

# Download node_exporter binary
- name: Check latest node_exporter
  uri:
    url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
    return_content: true
  register: nodeexporter_latest
  become: true

- name: "Installing node_exporter {{ nodeexporter_latest.json.tag_name }}"
  loop: "{{ nodeexporter_latest.json.assets }}"
  when: "'linux-amd64' in item.name"
  unarchive:
    remote_src: yes
    src: "{{ item.browser_download_url }}"
    dest: "/usr/local/bin/"
    mode: "+x"
    keep_newer: yes
    extra_opts:
    - --strip=1
    - --no-anchored
    - node_exporter
  become: true

# Create systemd service file from template
- name: Create systemd service file from template
  template:
    dest: /etc/systemd/system/node_exporter.service
    src: node_exporter.service.j2
  become: true

# Enable and start service

- name: Enable and start service
  systemd:
    name: node_exporter
    enabled: true
    state: restarted
    daemon_reload: yes
  become: true

- name: Get Linux Groups list
  shell: "getent group | cut -d: -f1"
  register: linux_groups


- name: Check if this is a Cloudlinux server
  stat:
    path: /usr/sbin/cloudlinux-config
  register: cloudlinux_installed

- name: Add prometheus user to clsupergid group on cloudlinux servers
  user:
      name: prometheus
      create_home: no
      groups: clsupergid
      append: yes
  when: cloudlinux_installed.stat.exists and "clsupergid" in linux_groups.stdout_lines
  become: true

- name: Add prometheus user to nagios group on cloudlinux servers if clsupergid does not exist (<= lve-4.2)
  user:
      name: prometheus
      create_home: no
      groups: nagios
      append: yes
  when: cloudlinux_installed.stat.exists and "nagios" in linux_groups.stdout_lines and not "clsupergid" in linux_groups.stdout_lines
  become: true